### ISSUE TITLE
installation error on windows

### ISSUE THREAD

**Issue by JohnGriffiths** [NeuroTechX/EEG-ExPy#25]
Installation on windows just stopped working for me. 

Trying to figure out why. 

```bash

Collecting soundfile
  Using cached SoundFile-0.10.3.post1-py2.py3.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win_amd64.whl (689 kB)
Collecting sounddevice
  Using cached sounddevice-0.4.1-py3.cp32.cp33.cp34.cp35.cp36.cp37.cp38.cp39.pp32.pp33.pp34.pp35.pp36.pp37-none-win_amd64.whl (167 kB)
Collecting python-bidi
  Using cached python_bidi-0.4.2-py2.py3-none-any.whl (30 kB)
Collecting arabic_reshaper
  Using cached arabic_reshaper-2.1.1.tar.gz (18 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\john_griffiths\Miniconda3\envs\eeg-notebooks_test\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\john_griffiths\\AppData\\Local\\Temp\\pip-install-c_csvdrr\\future\\setup.py'"'"'; __file__='"'"'C:\\Users\\john_griffiths\\AppData\\Local\\Temp\\pip-install-c_csvdrr\\future\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\john_griffiths\AppData\Local\Temp\pip-pip-egg-info-k3w3_qc8'
         cwd: C:\Users\john_griffiths\AppData\Local\Temp\pip-install-c_csvdrr\future\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\john_griffiths\Miniconda3\envs\eeg-notebooks_test\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\john_griffiths\\AppData\\Local\\Temp\\pip-install-c_csvdrr\\future\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

(eeg-notebooks_test) C:\Users\john_griffiths\Code\libraries_of_mine\github\eeg-notebooks>


```

**Comment by JohnGriffiths** [comment]
working now.
